apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: app

patchesStrategicMerge:
- patch.yaml

commonLabels:
  environment: dev
images:
- name: registry.example.com/app/frontend
  newTag: "24912078"
