apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: wheelloader

patchesStrategicMerge:
- patch.yaml

commonLabels:
  environment: dev
images:
- name: harbor.clobotspot.com/wheelloader/frontend
  newTag: "24912078"
