apiVersion: v1
kind: Service
metadata:
  name: core-server-svc
spec:
  externalIPs:
  - 172.30.1.239
  selector:
    app: core-server
  ports:
  - protocol: TCP
    name: fiber
    port: 6010
    targetPort: 6010
  - protocol: TCP
    name: grpc
    port: 26030
    targetPort: 26030
  type: ClusterIP