apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-server
  template:
    spec:
      containers:
      - name: core-server
        image: harbor.clobotspot.com/wheelloader/core-server:latest
        resources:
          limits:
            cpu: "6"  # 0.5 CPU cores
            memory: "8196Mi"  # 512 MiB memory
          requests:
            cpu: "4"  # 0.2 CPU cores requested
            memory: "4096Mi"  # 256 MiB memory requested