# VLAgent - VictoriaLogs 로그 수집 에이전트 (개발환경)
# 차트: vm/victoria-logs-agent

# 리소스 설정 (개발환경)
resources:
  requests:
    memory: "50Mi"
    cpu: "25m"
  limits:
    memory: "100Mi"
    cpu: "100m"

# 로그 전송 대상 (VictoriaLogs)  
remoteWrite:
  url: http://victoria-logs-single.monitoring.svc.cluster.local:9428/insert/jsonline

# DaemonSet으로 모든 노드에 배포
daemonSet: true

# 로그 수집 설정 (간소화)
config:
  # 컨테이너 로그 수집
  - input_plugin: "kubernetes"
    kubernetes:
      # Kubernetes API 설정
      api_server: "https://kubernetes.default.svc:443"
      tls_ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt" 
      token_file: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      
      # 로그 파일 경로
      log_path: "/var/log/containers/*.log"
      
      # 파서 설정
      parser: "docker"
      
      # 메타데이터 추가 (최소)
      annotations: false
      labels: true
      
    # 필터링
    filters:
      # Kubernetes 메타데이터 추가
      - plugin: "kubernetes_metadata"
        config:
          merge_log: true
          preserve_original_log: false
          
      # 시스템 네임스페이스 제외
      - plugin: "grep"
        config:
          exclude: |
            kubernetes_namespace_name kube-system
            kubernetes_namespace_name kube-public
            
    # 출력 설정
    output:
      plugin: "victoria_logs"
      config:
        url: "http://victoria-logs-single.monitoring.svc.cluster.local:9428/insert/jsonline"
        format: "json"
        timeout: "5s"
        retry_limit: 2

# 볼륨 마운트 설정
volumeMounts:
  - name: varlog
    mountPath: /var/log
    readOnly: true
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true

volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers

# ServiceAccount 권한 설정
rbac:
  create: true
  rules:
    - apiGroups: [""]
      resources: ["pods", "nodes", "namespaces"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["pods/log"] 
      verbs: ["get"]

serviceAccount:
  create: true
  name: ""

# 서비스 설정
service:
  enabled: true
  type: ClusterIP
  port: 8427
  targetPort: 8427

# 보안 설정
securityContext:
  privileged: true
  runAsUser: 0

# Tolerations
tolerations:
  - effect: NoSchedule
    operator: Exists

# 환경변수
env:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName