fullnameOverride: "victoria-logs"

server:
  # 개발환경 - 7일 보존
  retentionPeriod: "7d"
  
  # Loki API 호환 모드 활성화
  extraArgs:
    envflag.enable: true
    envflag.prefix: VM_
    loggerFormat: json
    httpListenAddr: :9428
    http.shutdownDelay: 15s
    # Loki 호환 엔드포인트 활성화
    # loki.tenantID: "0"
    # loki.maxQuerySize: "1000"
    # 로그 볼륨 기능 활성화
    # loki.volumeEnabled: "true"
  
  # 개발환경 - 낮은 리소스
  resources:
    requests:
      memory: "200Mi"
      cpu: "100m"
    limits:
      memory: "500Mi" 
      cpu: "500m"
      
  persistentVolume:
    enabled: true
    # 개발환경 - 10GB
    size: 10Gi
    storageClass: ""  # 기본 스토리지 클래스 사용
    
  service:
    type: ClusterIP
    clusterIP: ""
    servicePort: 9428
    externalIPs:
      - 192.168.0.10
  ingress:
    enabled: false

dashboards:
  # -- Create VictoriaLogs dashboards
  enabled: true
  # -- Dashboard labels
  labels: {}
  #  grafana_dashboard: "1"
  # -- Dashboard annotations
  annotations: {}
  # -- Override default namespace, where to create dashboards
  namespace: "monitoring"
  grafanaOperator:
    enabled: true
    spec:
      # instanceSelector:
      #   matchLabels:
      #     dashboards: "grafana"
      allowCrossNamespaceImport: true
# Vector 활성화 (로그 수집)
# vector:
#   enabled: true