# Grafana Tempo - 분산 트레이싱
# 차트: grafana/tempo

tempo:
  # 리소스 설정
  resources:
    requests:
      memory: "200Mi"
      cpu: "100m"
    limits:
      memory: "500Mi"
      cpu: "500m"
  
  # 스토리지 설정
  persistence:
    enabled: true
    size: 20Gi
    storageClassName: ""  # 기본 스토리지 클래스 사용
    
  # 서비스 설정 (externalIPs 사용)
  service:
    type: ClusterIP
    port: 3100
    externalIPs:
      - ${EXTERNAL_IP}  # 실제 서버 IP로 변경 필요
    
  # Tempo 구성
  tempo:
    # 보존 기간
    retention: "168h"  # 7일
    
    # 수신자 설정
    receivers:
      jaeger:
        protocols:
          thrift_http:
            endpoint: 0.0.0.0:14268
          grpc:
            endpoint: 0.0.0.0:14250
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      zipkin:
        endpoint: 0.0.0.0:9411
    
    # 스토리지 구성
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
          
  # Ingress 설정 (필요시 활성화)
  ingress:
    enabled: false
    # enabled: true
    # hosts:
    #   - host: tempo.local
    #     paths:
    #       - path: /
    #         pathType: Prefix